// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRqEQoYgzsxkqxkH7_-n5gfsDjWj5lmk',
    appId: '1:626234036171:web:fec1180a43885d153d704e',
    messagingSenderId: '626234036171',
    projectId: 'store-letushops',
    authDomain: 'store-letushops.firebaseapp.com',
    storageBucket: 'store-letushops.firebasestorage.app',
    measurementId: 'G-MY8LYYWJP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwWt1FLDQI6JsT88GcLnbb9NgtqSgK5o',
    appId: '1:626234036171:android:cbe9b3fe7dd086cd3d704e',
    messagingSenderId: '626234036171',
    projectId: 'store-letushops',
    storageBucket: 'store-letushops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2wRi3ZlzIxqjgANa4Bmt7IwyPj5S83hw',
    appId: '1:626234036171:ios:68945d65476ff5063d704e',
    messagingSenderId: '626234036171',
    projectId: 'store-letushops',
    storageBucket: 'store-letushops.firebasestorage.app',
    iosBundleId: 'com.example.stockLetuShops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2wRi3ZlzIxqjgANa4Bmt7IwyPj5S83hw',
    appId: '1:626234036171:ios:68945d65476ff5063d704e',
    messagingSenderId: '626234036171',
    projectId: 'store-letushops',
    storageBucket: 'store-letushops.firebasestorage.app',
    iosBundleId: 'com.example.stockLetuShops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRqEQoYgzsxkqxkH7_-n5gfsDjWj5lmk',
    appId: '1:626234036171:web:a2bb528cf9f7cad43d704e',
    messagingSenderId: '626234036171',
    projectId: 'store-letushops',
    authDomain: 'store-letushops.firebaseapp.com',
    storageBucket: 'store-letushops.firebasestorage.app',
    measurementId: 'G-QEE6QY7KPM',
  );

}